create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10,2) not null,
  category text not null,
  available boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  schedule_at timestamptz not null,
  slots integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.guest_orders (
  id bigint generated by default as identity primary key,
  room_number text not null,
  status text not null default 'pending',
  total_amount numeric(10,2) not null default 0,
  created_at timestamptz not null default now()
);
